### ISSUE TITLE
Resaltar mucho mas la fecha, añadiendo tambien el lugar

### ISSUE THREAD

**Issue by jonathanvila** [dev-bcn/website#27]
Añadir el año 2023, y debajo "La Farga, Hospitalet, Barcelona", y que resalte mucho mas, con un background como DevBcn ?

![image](https://user-images.githubusercontent.com/1836434/205609300-9e74ef0a-4dfc-487a-9552-dea1514ed66e.png)

**Comment by anyulled** [comment]
El año ya está arriba, ¿lo muevo abajo entonces?
